services:
  store-manager:
    image: store-manager
    build:
      context: .
      dockerfile: StoreManager/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=db;Database=StoreManager;User=sa;Password=Password!123
  
  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
